name: publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 22
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo corepack enable
          corepack yarn
      - name: Package
        run: yarn run pack
      - name: Upload to Github Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: mp-oi-library.vsix
      - name: Publish to VS Code Marketplace
        run: yarn run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
